### ISSUE TITLE
Default credentials

### ISSUE THREAD

**Issue by kyphosis** [gonenduk/basejs#2]
How does one figure out what is default credentials for admin to create new assets in the database?

**Comment by gonenduk** [comment]
Remember this is just a skeleton of a server. It is not a boilerplate, not a wizard or anything else like that. You simple clone the code, delete what you don't need, and edit and change what you need to add.
The DB is not created by default. Under tools I have created a simple db tool to create the DB of the example, define the schema and add 3 user types (admin, moderator and normal user).
You can run it from the command line with:
npm run db
To reset the DB and create all users from scratch, simple run:
npm run db clean init users

**Comment by efukela** [comment]
Gotcha.
When migrating to linux i can't produce the commands, getting `Command 'init' failed: unknown top level operator: $jsonSchema
`

**Comment by gonenma** [comment]
Check your mongo DB version.
You need version 3.6 and up to use $jsonSchema

**Comment by efukela** [comment]
Thank you, for some reason I don't have option to close this, so perhaps could you close it?
